Neural Networks is an ML algorithm where we train a model based on some data, by adjusting weights and biases to give better predictions. When we say the model is becoming better, we mean that the value of the cost function is going down after each round of gradient descent. Once the training phase is over, the data is discarded and the weights and biases are fixed. As new data flows in, the network makes predictions based on these fixed parameters. This phase is refered to as inference.

In [1]:
import numpy as np

In [113]:
w1 = np.random.randn(4, 3) # weights connecting input to hidden
b1 = np.random.randn(4,) # biases for hidden layer
w2 = np.random.randn(2, 4) # weights connecting hidden to output
b2 = np.random.randn(2,) # biases for output layer
print("w1\n" ,w1)
print("b1\n" ,b1)
print("w2\n" ,w2)
print("b2\n" ,b2)

w1
 [[ 1.33244722  0.70039275  0.26483249]
 [-2.63651626 -1.78387454 -0.78559856]
 [ 0.45539287  0.37786446 -0.25462176]
 [ 0.09593033 -1.12220922 -0.87040044]]
b1
 [-0.91524709  0.36774806  0.24113587 -1.85732071]
w2
 [[ 0.81760391 -0.23891531 -0.84157834  1.76132607]
 [-0.91909588  0.40905918 -1.46812202  0.58626444]]
b2
 [ 0.83507959 -0.55668326]


In [75]:
data_train = np.random.randn(10,3)
a = np.array([0,1]) 
data_train_ans = np.repeat(a,5)
np.random.shuffle(data_train_ans)
print("data train\n", data_train)
print("data train ans\n",data_train_ans) 

data train
 [[ 1.31228435  0.4500174  -1.19225002]
 [ 0.47008478 -0.82991488 -0.26753618]
 [-0.53718969  0.7673423   1.87334453]
 [-1.5337375  -0.41249456 -0.99365469]
 [ 0.79456276  0.17609382  1.76103986]
 [ 0.68477288 -1.98421292  1.84602629]
 [ 0.46041798 -0.45158312 -2.38708418]
 [-0.08854454 -2.35140661 -2.16078514]
 [ 0.53034723 -0.33076006 -0.51361423]
 [ 1.31279041  0.18202689  0.91211947]]
data train ans
 [1 1 0 1 1 0 0 0 0 1]


In [162]:
# Class 0 — points around (1, 1, 1)
X_class0 = np.random.randn(50, 3) + np.array([1, 1, 1])

# Class 1 — points around (-1, -1, -1)
X_class1 = np.random.randn(50, 3) + np.array([-1, -1, -1])

# Stack them together
data_train = np.vstack([X_class0, X_class1])
data_train_ans = np.array([0]*50 + [1]*50)

In [161]:
w1 = np.random.randn(4, 3) * 0.01
b1 = np.random.randn(4) * 0.01
w2 = np.random.randn(2, 4) * 0.01
b2 = np.random.randn(2) * 0.01

In [76]:
def forward(data_train,w1,b1,w2,b2):
    v1 = data_train @ w1.T + b1 
    a1 = np.maximum(0,v1)
    v2 = a1 @ w2.T + b2
    n = np.exp(v2)
    a2 = n / np.sum(n, axis = 1, keepdims = True)
    return a2 , a1 , v2, v1

In [149]:
def cross_entropy_loss(data_train_ans, a2):
    indi_loss = -1*np.log(a2[np.arange(len(a2)), data_train_ans]) #shape = (10,1)
    loss = np.mean(indi_loss)
    return loss

In [78]:
cross_entropy_loss(data_train_ans,a2)

np.float64(0.6931471805599453)

In [117]:
def one_hot(data_train_ans,n_classes):
    mat = np.zeros((len(data_train_ans),n_classes))
    mat[np.arange(len(data_train_ans)), data_train_ans] = 1
    return mat
one_hot(data_train_ans,2)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [135]:
def backprop(data_train, data_train_ans , a2, a1, v2, v1, w2,n_classes):
    one_hot_y = one_hot(data_train_ans,n_classes)
    dv2 = a2 - one_hot_y
    dw2 = dv2.T @ a1 / len(data_train_ans)
    db2 = np.mean(dv2, axis=0)
    da1 = dv2 @ w2
    dv1 = da1 * (v1 > 0)
    dw1 = dv1.T @ data_train / len(data_train_ans)
    db1 = np.mean(dv1, axis=0)
    return dw1,db1,dw2,db2
backprop(data_train, data_train_ans , a2, a1, v2, v1, w2,2)

ValueError: operands could not be broadcast together with shapes (10,2) (100,2) 

In [97]:
def update_params(w1, b1, w2, b2, dw1, db1, dw2, db2, learning_rate):
    w1 = w1 - learning_rate * dw1
    b1 = b1 - learning_rate * db1
    w2 = w2 - learning_rate * dw2
    b2 = b2 - learning_rate * db2
    return w1,b1,w2,b2

In [166]:
def training(data_train,data_train_ans,w1,b1,w2,b2,n_classes):
    for _ in range(5000):
        a2,a1,v2,v1 = forward(data_train,w1,b1,w2,b2)
        loss = cross_entropy_loss(data_train_ans, a2)
        dw1,db1,dw2,db2 = backprop(data_train, data_train_ans , a2, a1, v2, v1, w2,n_classes)
        w1,b1,w2,b2 = update_params(w1, b1, w2, b2, dw1, db1, dw2, db2, 0.1)
        if _ % 100 == 0:
            print("loss : ", loss)
    return w1, b1, w2, b2
    
w1, b1, w2, b2 = training(data_train, data_train_ans, w1, b1, w2, b2,2)

loss :  0.0678592118219857
loss :  0.0678496173258993
loss :  0.06784084667469138
loss :  0.0678321561259137
loss :  0.06782298061087504
loss :  0.06781456376530975
loss :  0.06780635080929433
loss :  0.06779760180020795
loss :  0.06778984849865127
loss :  0.06778156774618553
loss :  0.06777337959119249
loss :  0.06776527916472325
loss :  0.06775828112954162
loss :  0.06775081813466562
loss :  0.06774343255785557
loss :  0.06773613167340307
loss :  0.06772831074001257
loss :  0.0677211309860589
loss :  0.06771404174706157
loss :  0.06770650094785846
loss :  0.06769987467935717
loss :  0.06769334625275118
loss :  0.06768632821047701
loss :  0.06767992512300426
loss :  0.06767317723137442
loss :  0.06766655554651478
loss :  0.0676599881532882
loss :  0.06765405627871894
loss :  0.06764764060246979
loss :  0.06764129622228036
loss :  0.06763511440846962
loss :  0.06762900639178876
loss :  0.06762299768050978
loss :  0.06761657296086737
loss :  0.06761088845538833
loss :  0.067605257547823

In [158]:
def accuracy(array1, array2):
    a = array1 == array2
    accu = (np.sum(a) / len(array1)) * 100
    return accu 

In [167]:
a2,a1,v2,v1 = forward(data_train,w1,b1,w2,b2)
predictions = np.argmax(a2, axis=1)
accuracy(predictions, data_train_ans)

np.float64(95.0)